nov_core_food_index:
    pattern:  /menu
    defaults: { _controller: NovCoreBundle:Food:index }

nov_core_photo_index:
    pattern:  /photos
    defaults: { _controller: NovCoreBundle:Photo:index }

nov_core_contact_index:
    pattern:  /contact
    defaults: { _controller: NovCoreBundle:Contact:index }

nov_core_reservation_index:
    pattern:  /reservation
    defaults: { _controller: NovCoreBundle:Reservation:index }
